# Generated by Django 2.2.6 on 2019-11-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_auto_20191025_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_public_key', models.TextField()),
                ('hd', models.NullBooleanField()),
                ('name', models.TextField()),
                ('token', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet',
            field=models.TextField(null=True),
        ),
    ]
