# Generated by Django 2.2.6 on 2019-10-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0003_auto_20191015_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_api_key',
            field=models.TextField(default='stynikdnidniwanifjnilnonfwbfubuabwfubuwaf'),
            preserve_default=False,
        ),
    ]
