# Generated by Django 2.2.6 on 2019-10-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0004_customuser_user_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_api_key',
            new_name='api_key',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='user_karma',
            new_name='karma',
        ),
    ]
