# Generated by Django 2.2.6 on 2019-10-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0005_auto_20191025_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='api_key',
        ),
    ]
