# Generated by Django 2.2.6 on 2019-10-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0008_karmaobjections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KarmaObjections',
            new_name='KarmaObjection',
        ),
    ]
