# Generated by Django 2.2.6 on 2019-11-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0009_auto_20191031_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='api_key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='karma',
            field=models.IntegerField(null=True),
        ),
    ]
