# Generated by Django 2.2.6 on 2019-10-15 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 12, 47, 15, 86849)),
        ),
    ]
