# Generated by Django 2.2.6 on 2019-10-15 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_auto_20191015_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_upvotes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
