# Generated by Django 2.2.6 on 2019-10-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_auto_20191015_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_cost',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_upvotes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_views',
            field=models.IntegerField(default='0'),
        ),
    ]
