# Generated by Django 2.2.6 on 2019-10-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_auto_20191015_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_upvotes',
            new_name='upvotes',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_views',
            new_name='views',
        ),
    ]
